// <auto-generated />
namespace Grater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fds1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fds1));
        
        string IMigrationMetadata.Id
        {
            get { return "201906052119499_fds1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
